blueprint:
  name: "Aquarium Smart Lighting Control"
  description: >
    Aquarium lighting control with power monitoring and brightness level control
    via button press simulation. Converted from Node-RED flow.
    
    FIRST: Create input number helper for brightness control (min:0, max:3, step:1)
    THEN: Use this blueprint with your smart socket and power sensor.
  
  domain: automation
  
  input:
    aquarium_switch:
      name: "Aquarium Smart Socket"
      description: "Smart socket that controls the aquarium lights and monitors power consumption"
      selector:
        entity:
          domain: switch
    
    power_sensor:
      name: "Power Consumption Sensor"
      description: "Sensor that monitors the power consumption of the aquarium lights (usually from the smart socket)"
      selector:
        entity:
          domain: sensor
          device_class: power
    
    brightness_control:
      name: "Brightness Control Input"
      description: "Input number that controls light intensity (0=off, 1=low, 2=medium, 3=high). Create this in Helpers first."
      selector:
        entity:
          domain: input_number

variables:
  # Power thresholds (based on original Node-RED values)
  threshold_0: 0.5    # 0-0.5W = Level 0 (off)
  threshold_1: 5.0    # 0.5-5W = Level 1 (low)
  threshold_2: 9.0    # 6-9W = Level 2 (medium)
  threshold_3: 15.0   # 11-15W = Level 3 (high)

trigger:
  # Brightness setting changes (immediate response)
  - platform: state
    entity_id: !input brightness_control
    id: "brightness_changed"
  
  # Power monitoring trigger
  - platform: state
    entity_id: !input power_sensor
    id: "power_changed"
  
  # Brightness control trigger with delay (for button simulation)
  - platform: state
    entity_id: !input brightness_control
    for:
      seconds: 2
    id: "brightness_control_trigger"
  
  # Home Assistant start
  - platform: homeassistant
    event: start
    id: "ha_start"

condition: []

action:
  - variables:
      trigger_id: "{{ trigger.id | default('unknown') }}"
      brightness_input: !input brightness_control
      power_input: !input power_sensor  
      switch_input: !input aquarium_switch
      current_brightness: "{{ states(brightness_input) | float(0) }}"
      current_power: "{{ states(power_input) | float(0) }}"
      current_switch_state: "{{ states(switch_input) }}"

      # Create unique helper entity names based on aquarium switch
      helper_prefix: "{{ switch_input.split('.')[1] }}"
      trwa_zmiana_entity: "input_boolean.{{ helper_prefix }}_trwa_zmiana"
      zablokowano_entity: "input_boolean.{{ helper_prefix }}_zablokowano"
      current_level_entity: "input_number.{{ helper_prefix }}_current_level"
      
      # Helper entity states (with fallbacks if entities don't exist)
      trwa_zmiana: "{{ states(trwa_zmiana_entity) == 'on' if states(trwa_zmiana_entity) != 'unknown' else false }}"
      zablokowano: "{{ states(zablokowano_entity) == 'on' if states(zablokowano_entity) != 'unknown' else false }}"
      current_level: "{{ states(current_level_entity) | int(0) if states(current_level_entity) != 'unknown' else 0 }}"

  # TRACE: Log every automation trigger
  - service: system_log.write
    data:
      message: "{{ helper_prefix }}: AUTOMATION TRIGGERED - ID: {{ trigger_id }}, Brightness: {{ current_brightness }}, Power: {{ current_power }}W, Switch: {{ current_switch_state }}"
      level: warning

  # Route to appropriate logic based on trigger
  - choose:
      # BRIGHTNESS CHANGED - Simple on/off control
      - conditions:
          - condition: template
            value_template: "{{ trigger_id in ['brightness_changed', 'ha_start'] }}"
        sequence:
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: BRIGHTNESS CONTROL TRIGGERED - Current: {{ current_brightness }}"
              level: warning
          - choose:
              # If brightness is 0, turn off
              - conditions:
                  - condition: template
                    value_template: "{{ current_brightness == 0 }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input aquarium_switch
                  - service: system_log.write
                    data:
                      message: "{{ helper_prefix }}: OFF - brightness set to 0"
                      level: info
              
              # If brightness > 0, turn on
              - conditions:
                  - condition: template
                    value_template: "{{ current_brightness > 0 }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input aquarium_switch
                  - service: system_log.write
                    data:
                      message: "{{ helper_prefix }}: ON - brightness set to {{ current_brightness }}"
                      level: info

      # POWER MONITORING (from Node-RED power sensor logic)
      - conditions:
          - condition: template
            value_template: "{{ trigger_id in ['power_changed', 'ha_start'] }}"
          - condition: template
            value_template: "{{ not trwa_zmiana }}"
        sequence:
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: POWER MONITORING TRIGGERED - Power: {{ current_power }}W, Current brightness: {{ current_brightness }}, trwa_zmiana: {{ trwa_zmiana }}"
              level: info
          - variables:
              detected_brightness: >
                {% if current_power >= 0 and current_power < threshold_0 %}
                  0
                {% elif current_power >= threshold_0 and current_power <= threshold_1 %}
                  1
                {% elif current_power > threshold_1 and current_power <= threshold_2 %}
                  2
                {% elif current_power > threshold_2 and current_power <= threshold_3 %}
                  3
                {% else %}
                  null
                {% endif %}
          
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: POWER ANALYSIS - {{ current_power }}W detected as level {{ detected_brightness }}, current setting: {{ current_brightness }}"
              level: info
          
          - condition: template
            value_template: "{{ detected_brightness is not none and detected_brightness != current_brightness }}"
          
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: BRIGHTNESS MISMATCH DETECTED - Power {{ current_power }}W suggests level {{ detected_brightness }}, but input is {{ current_brightness }} (not auto-updating)"
              level: warning
          
          # DISABLED: Auto-update of brightness input to prevent feedback loops
          # - service: input_number.set_value
          #   target:
          #     entity_id: !input brightness_control
          #   data:
          #     value: "{{ detected_brightness }}"
          
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: Power monitor {{ current_power }}W → brightness {{ detected_brightness }}"
              level: info

      # BUTTON PRESS SIMULATION (from Node-RED brightness change logic)
      - conditions:
          - condition: template
            value_template: "{{ trigger_id == 'brightness_control_trigger' }}"
          - condition: template
            value_template: "{{ not zablokowano }}"
        sequence:
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: BUTTON SIMULATION TRIGGERED - Target: {{ current_brightness }}, Current level: {{ current_level }}, Blocked: {{ zablokowano }}"
              level: info
          - variables:
              desired_level: "{{ current_brightness | int }}"
              
              # Determine current state - use power reading if recent, otherwise use stored level
              power_based_level: >
                {% if current_power >= 0 and current_power <= threshold_0 %}
                  0
                {% elif current_power > threshold_0 and current_power <= threshold_1 %}
                  1
                {% elif current_power > threshold_1 and current_power <= threshold_2 %}
                  2
                {% elif current_power > threshold_2 and current_power <= threshold_3 %}
                  3
                {% else %}
                  null
                {% endif %}
              
              # Use power-based level if available, otherwise use stored level, default to 0 if switch is off
              estimated_current: >
                {% if current_switch_state == 'off' %}
                  0
                {% elif power_based_level is not none %}
                  {{ power_based_level }}
                {% elif current_level > 0 %}
                  {{ current_level }}
                {% else %}
                  3
                {% endif %}
              
              # Calculate button presses needed (original Node-RED logic)
              button_presses: >
                {% set current = estimated_current | int %}
                {% set desired = desired_level %}
                {% if desired == 0 %}
                  0
                {% elif current == 0 %}
                  {% if desired == 1 %}5{% elif desired == 2 %}3{% elif desired == 3 %}1{% else %}0{% endif %}
                {% elif current == 1 %}
                  {% if desired == 2 %}4{% elif desired == 3 %}2{% else %}0{% endif %}
                {% elif current == 2 %}
                  {% if desired == 1 %}2{% elif desired == 3 %}4{% else %}0{% endif %}
                {% elif current == 3 %}
                  {% if desired == 1 %}4{% elif desired == 2 %}2{% else %}0{% endif %}
                {% else %}0{% endif %}
              
              needs_turn_off: "{{ desired_level == 0 }}"
              is_currently_off: "{{ current_switch_state == 'off' or estimated_current == 0 }}"

          # Set change in progress (if helper exists)
          - if:
              - condition: template
                value_template: "{{ states(trwa_zmiana_entity) != 'unknown' }}"
            then:
              - service: input_boolean.turn_on
                target:
                  entity_id: "{{ trwa_zmiana_entity }}"

          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: CONTROL PLAN - Current: {{ estimated_current }}, Target: {{ desired_level }}, Button presses: {{ button_presses }}, Switch state: {{ current_switch_state }}"
              level: info

          - choose:
              # Turn off case
              - conditions:
                  - condition: template
                    value_template: "{{ needs_turn_off }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input aquarium_switch
                  - service: system_log.write
                    data:
                      message: "{{ helper_prefix }}: TURNED OFF - Target brightness was 0"
                      level: info
              
              # Button press case - light is on and needs level change
              - conditions:
                  - condition: template
                    value_template: "{{ button_presses > 0 }}"
                sequence:
                  # Turn on first if currently off
                  - if:
                      - condition: template
                        value_template: "{{ is_currently_off }}"
                    then:
                      - service: switch.turn_on
                        target:
                          entity_id: !input aquarium_switch
                      - service: system_log.write
                        data:
                          message: "{{ helper_prefix }}: TURNED ON - Light was off, now at level 3"
                          level: info
                      - delay:
                          seconds: 2
                  
                  # Execute rapid on/off cycles to reach desired level
                  - service: system_log.write
                    data:
                      message: "{{ helper_prefix }}: CYCLING - Executing {{ button_presses }} rapid on/off cycles"
                      level: info
                  
                  - repeat:
                      count: "{{ button_presses }}"
                      sequence:
                        - service: switch.turn_off
                          target:
                            entity_id: !input aquarium_switch
                        - delay:
                            milliseconds: 100
                        - service: switch.turn_on
                          target:
                            entity_id: !input aquarium_switch
                        - delay:
                            milliseconds: 500
                  
                  - service: system_log.write
                    data:
                      message: "{{ helper_prefix }}: CYCLING COMPLETE - Should now be at level {{ desired_level }}"
                      level: info

          # Store expected level after button presses (if helper exists)
          - if:
              - condition: template
                value_template: "{{ states(current_level_entity) != 'unknown' }}"
            then:
              - service: input_number.set_value
                target:
                  entity_id: "{{ current_level_entity }}"
                data:
                  value: "{{ desired_level }}"
              - service: system_log.write
                data:
                  message: "{{ helper_prefix }}: LEVEL STORED - Expected level {{ desired_level }} saved for future calculations"
                  level: info
          
          # Wait for light to stabilize before allowing power monitoring
          - delay:
              seconds: 5
          
          - if:
              - condition: template
                value_template: "{{ states(trwa_zmiana_entity) != 'unknown' }}"
            then:
              - service: input_boolean.turn_off
                target:
                  entity_id: "{{ trwa_zmiana_entity }}"
              - service: system_log.write
                data:
                  message: "{{ helper_prefix }}: STABILIZATION COMPLETE - Power monitoring re-enabled"
                  level: info
          
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: Brightness change {{ current_level }} → {{ desired_level }} ({{ button_presses }} presses)"
              level: info

      # POWER MONITORING BLOCKED - Show when it's being skipped
      - conditions:
          - condition: template
            value_template: "{{ trigger_id in ['power_changed'] and trwa_zmiana }}"
        sequence:
          - service: system_log.write
            data:
              message: "{{ helper_prefix }}: POWER MONITORING BLOCKED - Change in progress (trwa_zmiana: {{ trwa_zmiana }})"
              level: info

    # CATCH-ALL: Log unhandled triggers
    default:
      - service: system_log.write
        data:
          message: "{{ switch_input.split('.')[1] }}: UNHANDLED TRIGGER - ID: {{ trigger_id }}, no matching conditions"
          level: warning

mode: single
max_exceeded: silent