blueprint:
  name: Climate Schedule Control
  description: Set climate temperature based on schedule with heating mode control
  domain: automation
  input:
    schedule_entity:
      name: Schedule
      description: Schedule entity that provides temperature values
      selector:
        entity:
          domain: schedule
    climate_entity:
      name: Climate Device
      description: Climate device to control
      selector:
        entity:
          domain: climate
    heating_mode_entity:
      name: Heating Mode Selector
      description: Input select entity that controls heating mode
      selector:
        entity:
          domain: input_select
    room_heating_mode_entity:
      name: Room Heating Mode Selector
      description: Input select entity that controls room heating mode
      selector:
        entity:
          domain: input_select

mode: single
triggers:
  - trigger: state
    entity_id:
      - !input schedule_entity
    attribute: temperature
  - trigger: state
    entity_id:
      - !input heating_mode_entity
  - trigger: state
    entity_id:
      - !input room_heating_mode_entity
conditions: []
actions:
  - variables:
      schedule_entity_id: !input schedule_entity
      heating_mode_entity_id: !input heating_mode_entity
      room_heating_mode_entity_id: !input room_heating_mode_entity
      main_heating_mode: >-
        {{ states(heating_mode_entity_id) }}
      room_heating_mode: >-
        {{ states(room_heating_mode_entity_id) }}
      effective_heating_mode: >-
        {% if main_heating_mode == 'Normalnie' %}
          {{ room_heating_mode }}
        {% else %}
          {{ main_heating_mode }}
        {% endif %}
  - if:
      - condition: template
        value_template: "{{ effective_heating_mode == 'Normalnie' }}"
    then:
      - action: climate.set_temperature
        target:
          entity_id: !input climate_entity
        data:
          hvac_mode: heat
          temperature: "{{ (state_attr(schedule_entity_id, 'temperature') or 16) | float(16) }}"
    else:
      - action: climate.set_temperature
        target:
          entity_id: !input climate_entity
        data:
          hvac_mode: 'off'
          temperature: 16.0
